version: '3.8'
services:
  appseed-app:
    restart: always
    env_file: .env
    build: .
    hostname: "dashboard"
    volumes:
      - /home:/home
      - /nbhome:/nbhome
      - /archive:/archive
      - ./certs:/etc/nginx/certs
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    networks:
      - web_network
    depends_on: 
      - appseed-app
  mariadb:
    restart: always
    env_file: .dbenv
    build: mariadb
    hostname: "dbserver"
    #volumes:
    #  - ./persist:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_network
    

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
