version: '3'
services:
  mariadb:
    env_file: .dbenv
    build: mariadb
    hostname: "dbserver"
    expose:
      - "3306"
    networks:
      - db_network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
    volumes:
     - /sessions
    networks:
      - db_network
    depends_on: 
      - mariadb
  webapp:
    env_file: .env
    build: .
    hostname: "dashboard"
    ports:
      - "5050:5050"
    networks:
      - db_network
    depends_on: 
      - mariadb

networks:
  db_network:
    driver: bridge
