version: '3'
services:
  mariadb:
    restart: always
    env_file: .dbenv
    build: mariadb
    hostname: "dbserver"
    #volumes:
    #  - ./persist:/var/lib/mysql
    networks:
      - db_network
  appseed-app:
    restart: always
    env_file: .env
    build: .
    hostname: "dashboard"
    volumes:
      - /Users/krasting/dbverif5:/Users/krasting/dbverif5
      - ./certs:/etc/certificates
    ports:
      - "5005:5005"
    networks:
      - db_network
    depends_on: 
      - mariadb

networks:
  db_network:
    driver: bridge
