FROM mariadb:latest

ENV MYSQL_ROOT_PASSWORD rootpassword
ENV MYSQL_DATABASE mdt_tracker
ENV MYSQL_USER mdtadmin
ENV MYSQL_PASSWORD adminpassword

EXPOSE 3306

COPY backup.sql /docker-entrypoint-initdb.d/backup.sql
RUN chmod ugo+rx /docker-entrypoint-initdb.d/backup.sql
